#if !canImport(ObjectiveC)
import XCTest

extension Base32Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Base32Tests = [
        ("testDecodeAlternatives", testDecodeAlternatives),
        ("testFiveLetters", testFiveLetters),
        ("testFourLetters", testFourLetters),
        ("testHelloWorld", testHelloWorld),
        ("testOneLetter", testOneLetter),
        ("testPartialDecoding", testPartialDecoding),
        ("testPartialDecoding2", testPartialDecoding2),
        ("testPartialEncoding", testPartialEncoding),
        ("testPartialEncoding2", testPartialEncoding2),
        ("testString1", testString1),
        ("testString2", testString2),
        ("testThreeLetters", testThreeLetters),
        ("testTwoLetters", testTwoLetters),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(Base32Tests.__allTests__Base32Tests),
    ]
}
#endif
